name: "build"

on: ["push", "pull_request"]

jobs:
  build-nix:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - run: nix build

  build-windows:
    runs-on: "windows-latest"

    steps:
    - uses: actions/checkout@v3

    - name: "login to AWS"
      uses: "aws-actions/configure-aws-credentials@v2"
      with:
        aws-region: us-east-2
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: "build"
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - name: "make installer"
      run: makensis install.nsi

    - uses: "actions/upload-artifact@v3"
      with:
        name: "windows installer"
        path: "green-installer.exe"
        if-no-files-found: error

    - name: "upload installer to S3"
      run: aws s3 cp green-installer.exe s3://green-updater/green-installer.exe

  build-macos:
    runs-on: "macos-latest"

    steps:
    - uses: actions/checkout@v3

    - name: "build"
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - uses: "actions/upload-artifact@v3"
      with:
        name: "macOS executable"
        path: "target/release/green-updater"
        if-no-files-found: error
